name: solana_wallet_provider
description: Provider widget for solana_web3 and solana_wallet_adapter packages.
repository: https://github.com/merigo-labs/solana-wallet-provider
issue_tracker: https://github.com/merigo-labs/solana-wallet-provider/issues/new/choose
version: 0.1.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  qr_flutter: ^4.1.0
  
  solana_common: ^0.1.0
    # path: ../solana_common
  solana_wallet_adapter: ^0.1.0
    # path: ../solana_wallet_adapter
  solana_web3: ^0.1.1
    # path: ../solana_web3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - icons/
  
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: SolanaWalletIcons
  #     fonts:
  #       - asset: fonts/SolanaWalletIcons.ttf

  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
